pipeline {
    agent any
    tools {
        maven 'maven'   
        jdk 'JDK'    
    }
    stages {
        stage('Build') {
    steps {
        bat 'mvn -B -DskipTests clean package'
        }
    }
        stage('Test') {
            steps {
                bat 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                   bat 'java -jar target/my-app.jar'
            }
        }
        stage('Complete') {
            steps {
                echo 'Job Complete!'
            }
        }
    }
}
